name: Build Java SB project
on:
  push:
    branches: [java-spring-boot]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - run: mkdir product && cp bank-customers-core-server/target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: product